from enum import Enum


class IngestionState(str, Enum):
    DISCOVERED = "DISCOVERED"
    FETCHING = "FETCHING"
    FETCHED = "FETCHED"
    SNAPSHOTTED = "SNAPSHOTTED"
    PARSED = "PARSED"
    EXTRACTED = "EXTRACTED"
    NORMALIZED = "NORMALIZED"
    VALIDATED = "VALIDATED"
    STAGED = "STAGED"
    PUBLISHED = "PUBLISHED"
    INDEXED = "INDEXED"
    COMPLETED = "COMPLETED"
    RETRYABLE_FAILED = "RETRYABLE_FAILED"
    QUARANTINED = "QUARANTINED"
    PERMANENT_FAILED = "PERMANENT_FAILED"


class PresenceState(str, Enum):
    SEEN = "SEEN"
    MISSING_CANDIDATE = "MISSING_CANDIDATE"
    CONFIRMED_MISSING = "CONFIRMED_MISSING"
